In [1]:
# chargement des données
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import metrics
from scipy.stats import chi2_contingency
import scipy.stats as stats
import os

In [3]:
hackhaton=pd.read_csv("hackhaton_020k_alea_b.csv",encoding='ISO-8859-1')
hackhaton.drop('Unnamed: 10', axis =1, inplace=True)
hackhaton.drop('Unnamed: 11', axis =1, inplace = True)

C:\Users\Paul Guiraud\AppData\Local\Temp\ipykernel_10156\1111744574.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  hackhaton=pd.read_csv("hackhaton_020k_alea_b.csv",encoding='ISO-8859-1')

In [178]:
hackhaton

,ID_CARRIERE,date_debut,date_fin,ETAT,CATEGORIE_EMPLOI,QUALITE,STATUT_AGENT,INDICE_BRUT,EMPLOI_STATUTAIRE,LIBELLE_EMPLOI_GRADE
0,56,01/01/1999,26/03/1999,1,A,T,T,NaN,NaN,ADJOINT ADMINISTRATIF.........
1,56,27/03/1999,16/07/1999,1,A,T,T,NaN,NaN,ADJOINT ADMINISTRATIF.........
2,56,17/07/1999,31/12/1999,1,A,T,T,NaN,NaN,ADJOINT ADMINISTRATIF.........
3,56,01/01/2000,02/07/2000,1,A,T,T,NaN,NaN,ADJOINT ADMINISTRATIF.........
4,56,03/07/2000,19/07/2000,1,A,T,T,NaN,NaN,ADJOINT ADMINISTRATIF.........
...,...,...,...,...,...,...,...,...,...,...
1048570,1861885,01/02/2009,28/02/2009,1,A,T,T,303.0,NaN,ADJ PAT 2C
1048571,1861885,01/03/2009,31/03/2009,1,A,T,T,303.0,NaN,ADJ PAT 2C
1048572,1861885,01/04/2009,08/04/2009,1,A,T,T,303.0,NaN,ADJ PAT 2C
1048573,1861885,09/04/2009,19/04/2009,1,A,T,T,303.0,NaN,ADJ PAT 2C
1048574,1861885,20/04/2009,30/04/2009,1,A,T,T,303.0,NaN,ADJ PAT 2C

La logique : 

Si un mec est echellon 0 en 5 ans, les 4 années précédentes il etait 0 aussi   
Si un mec est echellon 0, puis rien, puis echellon 0 -> echellon 0

In [222]:
code = hackhaton['EMPLOI_STATUTAIRE']
code=pd.DataFrame(code)
code.columns = ['1']
L= [a if type(a) == str else str(round(a,0)) for a in code['1']]

In [223]:
#Code pour chaque années de travail de chaque individus

index_to_code= dict(zip( [a for a in range(0, len(L))],L))
index_to_code

{0: 'nan',
 1: 'nan',
 2: 'nan',
 3: 'nan',
 4: 'nan',
 5: 'nan',
 6: 'nan',
 7: 'nan',
 8: 'nan',
 9: 'nan',
 10: 'nan',
 11: 'nan',
 12: 'nan',
 13: 'nan',
 14: 'nan',
 15: 'nan',
 16: 'nan',
 17: 'nan',
 18: 'nan',
 19: 'nan',
 20: 'nan',
 21: 'nan',
 22: 'nan',
 23: 'nan',
 24: 'nan',
 25: 'nan',
 26: 'nan',
 27: 'nan',
 28: 'nan',
 29: 'nan',
 30: 'nan',
 31: 'nan',
 32: 'nan',
 33: 'nan',
 34: 'nan',
 35: 'nan',
 36: 'nan',
 37: 'nan',
 38: 'nan',
 39: 'nan',
 40: 'nan',
 41: 'nan',
 42: 'nan',
 43: 'nan',
 44: 'nan',
 45: 'nan',
 46: 'nan',
 47: 'nan',
 48: 'nan',
 49: 'TNJ2',
 50: 'TNJ2',
 51: 'TNJ2',
 52: 'TNJ2',
 53: 'TNJ2',
 54: 'TNJ2',
 55: 'TNJ2',
 56: 'TNJ2',
 57: 'TNJ2',
 58: 'TNJ2',
 59: 'TNJ2',
 60: 'TNJ2',
 61: 'TNJ2',
 62: 'TNJ2',
 63: 'TNJ2',
 64: 'TNJ2',
 65: 'TNJ2',
 66: 'TNJ2',
 67: 'TNJ3',
 68: 'TNJ3',
 69: 'TNJ3',
 70: 'TNJ3',
 71: 'TNJ3',
 72: 'TNJ3',
 73: 'TNJ3',
 74: 'TNJ3',
 75: 'TNJ3',
 76: 'TNJ3',
 77: 'TNJ3',
 78: 'TNJ3',
 79: 'TNJ3',
 80: 'TNJ3',
 81: 'TNJ3',
 82: 'TNJ3',
 83: 'TNJ4',
 84: 'TNJ4',
 85: 'TNJ4',
 86: 'TNJ4',
 87: 'TNJ4',
 88: 'TNJ4',
 89: 'TNJ4',
 90: 'TNJ4',
 91: 'TNJ4',
 92: 'TNJ4',
 93: 'TNJ4',
 94: 'TNJ4',
 95: 'TNJ4',
 96: 'TNJ4',
 97: 'TNJ4',
 98: 'TNJ4',
 99: 'TNJ4',
 100: 'TNJ4',
 101: 'TNJ4',
 102: 'TNJ4',
 103: 'TNJ4',
 104: 'nan',
 105: 'nan',
 106: 'nan',
 107: 'nan',
 108: 'nan',
 109: 'nan',
 110: 'nan',
 111: 'nan',
 112: 'nan',
 113: 'nan',
 114: 'nan',
 115: 'nan',
 116: 'nan',
 117: 'nan',
 118: 'nan',
 119: 'nan',
 120: 'nan',
 121: 'nan',
 122: 'nan',
 123: 'nan',
 124: 'nan',
 125: 'nan',
 126: 'nan',
 127: 'nan',
 128: 'nan',
 129: 'TCJ1',
 130: 'TCJ1',
 131: 'TCJ1',
 132: 'TCJ1',
 133: 'TCJ1',
 134: 'TCJ1',
 135: 'TCJ1',
 136: 'TCJ1',
 137: 'TCJ1',
 138: 'TCJ1',
 139: 'TCJ2',
 140: 'TCJ2',
 141: 'TCJ2',
 142: 'TCJ2',
 143: 'TCJ2',
 144: 'nan',
 145: 'nan',
 146: 'nan',
 147: 'nan',
 148: 'nan',
 149: 'nan',
 150: 'nan',
 151: 'nan',
 152: 'nan',
 153: 'nan',
 154: 'nan',
 155: 'nan',
 156: 'nan',
 157: 'nan',
 158: 'nan',
 159: 'nan',
 160: 'nan',
 161: 'nan',
 162: 'nan',
 163: 'nan',
 164: 'nan',
 165: 'nan',
 166: 'nan',
 167: 'nan',
 168: 'nan',
 169: 'nan',
 170: 'nan',
 171: 'nan',
 172: 'nan',
 173: 'nan',
 174: 'nan',
 175: 'nan',
 176: 'nan',
 177: 'nan',
 178: 'nan',
 179: 'nan',
 180: 'nan',
 181: 'nan',
 182: 'nan',
 183: 'nan',
 184: 'nan',
 185: 'nan',
 186: 'nan',
 187: 'nan',
 188: 'nan',
 189: 'nan',
 190: 'nan',
 191: 'nan',
 192: 'nan',
 193: 'nan',
 194: 'nan',
 195: 'nan',
 196: 'nan',
 197: 'nan',
 198: 'nan',
 199: 'nan',
 200: 'nan',
 201: 'nan',
 202: 'nan',
 203: 'nan',
 204: 'nan',
 205: 'nan',
 206: 'nan',
 207: 'nan',
 208: 'nan',
 209: 'nan',
 210: 'nan',
 211: 'nan',
 212: 'nan',
 213: '2164',
 214: '2164',
 215: '2164',
 216: '2164',
 217: '2164',
 218: '2164',
 219: '2164',
 220: '2164',
 221: '2164',
 222: '2164',
 223: '2164',
 224: '2164',
 225: '2164',
 226: '2164',
 227: '2164',
 228: '2164',
 229: '2164',
 230: '2164',
 231: '2164',
 232: '2164',
 233: '2164',
 234: '2164',
 235: '2164',
 236: '2164',
 237: '2164',
 238: '2164',
 239: '2164',
 240: '2164',
 241: '2164',
 242: '2164',
 243: '2164',
 244: '2164',
 245: '2164',
 246: '2164',
 247: 'nan',
 248: 'nan',
 249: 'nan',
 250: 'nan',
 251: 'nan',
 252: 'nan',
 253: 'nan',
 254: 'nan',
 255: 'nan',
 256: 'nan',
 257: 'nan',
 258: 'nan',
 259: 'nan',
 260: 'nan',
 261: 'nan',
 262: 'nan',
 263: 'nan',
 264: 'nan',
 265: 'nan',
 266: 'nan',
 267: 'nan',
 268: 'nan',
 269: 'nan',
 270: 'nan',
 271: 'nan',
 272: 'TRS4',
 273: 'TRL1',
 274: 'TRL1',
 275: 'TRL1',
 276: 'TRL1',
 277: 'TRL1',
 278: 'TRL1',
 279: 'TRL1',
 280: 'TRL1',
 281: 'TRL1',
 282: 'TRL1',
 283: 'TRL1',
 284: 'TRL2',
 285: 'TRL2',
 286: 'TRL2',
 287: 'TRL2',
 288: 'TRL2',
 289: 'nan',
 290: 'nan',
 291: 'nan',
 292: 'nan',
 293: 'nan',
 294: 'nan',
 295: 'nan',
 296: 'nan',
 297: 'nan',
 298: 'nan',
 299: 'nan',
 300: 'nan',
 301: 'nan',
 302: 'nan',
 303: 'nan',
 304: 'nan',
 305: 'nan',
 306: 'nan',
 307: 'nan',
 308: 'nan',
 309: 'nan',
 310: 'nan',
 311: 'nan',
 312: 'nan',
 313: 'nan',
 314: 'nan',
 315: 'nan',
 316: 'nan',
 317: 'nan',
 318: 'nan',
 319: 'nan',
 320: 'nan',
 321: 'nan',
 322: 'nan',
 323: 'nan',
 324: 'nan',
 325: 'nan',
 326: 'nan',
 327: 'TTM2',
 328: 'TTM2',
 329: 'TTM2',
 330: 'TTM2',
 331: 'TTM2',
 332: 'TTM2',
 333: 'TTM2',
 334: 'TTM2',
 335: 'TTM2',
 336: 'TTM2',
 337: 'TTM2',
 338: 'TTM2',
 339: 'TTM2',
 340: 'TTM2',
 341: 'TTM2',
 342: 'TTM2',
 343: 'TTM2',
 344: 'TTM2',
 345: 'TTM2',
 346: 'TTM2',
 347: 'TTM2',
 348: 'TTM2',
 349: 'TTM2',
 350: 'TTM2',
 351: 'nan',
 352: 'nan',
 353: 'nan',
 354: 'nan',
 355: 'nan',
 356: 'nan',
 357: 'nan',
 358: 'nan',
 359: 'nan',
 360: 'nan',
 361: 'nan',
 362: 'nan',
 363: 'nan',
 364: 'nan',
 365: 'nan',
 366: 'nan',
 367: 'nan',
 368: 'nan',
 369: 'nan',
 370: 'nan',
 371: 'nan',
 372: 'nan',
 373: '2768',
 374: '2761',
 375: '2761',
 376: '2761',
 377: '2761',
 378: 'nan',
 379: '2761',
 380: '2761',
 381: '2761',
 382: '2761',
 383: 'nan',
 384: 'nan',
 385: 'nan',
 386: 'nan',
 387: 'nan',
 388: 'nan',
 389: 'nan',
 390: 'nan',
 391: 'nan',
 392: 'nan',
 393: 'nan',
 394: 'nan',
 395: 'nan',
 396: 'nan',
 397: 'nan',
 398: 'nan',
 399: 'nan',
 400: 'nan',
 401: 'nan',
 402: 'nan',
 403: 'nan',
 404: 'nan',
 405: 'nan',
 406: 'nan',
 407: 'nan',
 408: 'nan',
 409: 'nan',
 410: 'nan',
 411: 'nan',
 412: 'nan',
 413: 'nan',
 414: 'nan',
 415: 'nan',
 416: 'nan',
 417: 'nan',
 418: 'nan',
 419: 'nan',
 420: 'nan',
 421: 'nan',
 422: 'nan',
 423: 'nan',
 424: 'nan',
 425: 'nan',
 426: 'nan',
 427: 'nan',
 428: 'nan',
 429: 'nan',
 430: 'nan',
 431: 'nan',
 432: 'nan',
 433: 'nan',
 434: 'nan',
 435: 'nan',
 436: 'nan',
 437: 'nan',
 438: '1326',
 439: '1326',
 440: '1326',
 441: '1326',
 442: '1326',
 443: '1326',
 444: '1326',
 445: '1326',
 446: '1326',
 447: '1326',
 448: '1326',
 449: '1326',
 450: '1326',
 451: '1326',
 452: '1326',
 453: '1326',
 454: '1326',
 455: '1317',
 456: '1317',
 457: '1317',
 458: '1317',
 459: '1317',
 460: '1317',
 461: '1317',
 462: '1317',
 463: '1317',
 464: 'nan',
 465: 'nan',
 466: 'nan',
 467: 'nan',
 468: 'nan',
 469: 'nan',
 470: 'nan',
 471: 'nan',
 472: 'nan',
 473: 'nan',
 474: 'nan',
 475: 'nan',
 476: 'nan',
 477: 'nan',
 478: 'nan',
 479: 'nan',
 480: 'nan',
 481: 'nan',
 482: 'nan',
 483: 'nan',
 484: 'nan',
 485: 'nan',
 486: 'nan',
 487: 'nan',
 488: 'nan',
 489: 'nan',
 490: 'nan',
 491: 'nan',
 492: 'nan',
 493: 'nan',
 494: 'nan',
 495: 'nan',
 496: 'nan',
 497: 'nan',
 498: 'nan',
 499: 'nan',
 500: 'nan',
 501: 'nan',
 502: 'nan',
 503: 'nan',
 504: 'nan',
 505: 'nan',
 506: 'nan',
 507: 'nan',
 508: 'nan',
 509: 'nan',
 510: 'nan',
 511: 'nan',
 512: 'nan',
 513: 'nan',
 514: 'nan',
 515: 'nan',
 516: 'nan',
 517: 'nan',
 518: 'nan',
 519: 'nan',
 520: 'nan',
 521: 'nan',
 522: 'nan',
 523: 'nan',
 524: 'nan',
 525: 'nan',
 526: 'nan',
 527: 'nan',
 528: 'nan',
 529: 'nan',
 530: 'nan',
 531: 'nan',
 532: 'nan',
 533: 'nan',
 534: 'nan',
 535: 'nan',
 536: 'nan',
 537: 'nan',
 538: 'nan',
 539: 'nan',
 540: 'nan',
 541: 'nan',
 542: 'nan',
 543: 'nan',
 544: 'nan',
 545: 'nan',
 546: 'nan',
 547: 'nan',
 548: 'nan',
 549: 'nan',
 550: 'nan',
 551: 'nan',
 552: 'nan',
 553: 'nan',
 554: 'nan',
 555: 'nan',
 556: 'nan',
 557: 'nan',
 558: 'nan',
 559: 'nan',
 560: 'nan',
 561: 'nan',
 562: 'nan',
 563: 'nan',
 564: 'nan',
 565: 'nan',
 566: 'nan',
 567: 'nan',
 568: 'nan',
 569: 'nan',
 570: 'nan',
 571: 'nan',
 572: 'nan',
 573: 'nan',
 574: 'nan',
 575: 'nan',
 576: 'nan',
 577: 'nan',
 578: 'nan',
 579: 'nan',
 580: 'nan',
 581: 'nan',
 582: 'nan',
 583: 'nan',
 584: 'nan',
 585: 'nan',
 586: 'nan',
 587: 'nan',
 588: 'nan',
 589: 'nan',
 590: 'nan',
 591: 'nan',
 592: 'nan',
 593: 'nan',
 594: 'nan',
 595: 'nan',
 596: 'nan',
 597: 'nan',
 598: 'nan',
 599: 'nan',
 600: 'nan',
 601: 'nan',
 602: 'nan',
 603: 'nan',
 604: 'nan',
 605: 'nan',
 606: 'nan',
 607: 'nan',
 608: '4324',
 609: '4324',
 610: '4324',
 611: '4324',
 612: '4324',
 613: '4324',
 614: '4324',
 615: '4324',
 616: '4324',
 617: '4324',
 618: '4324',
 619: '4324',
 620: '4330',
 621: '4330',
 622: '4330',
 623: '4330',
 624: '4330',
 625: '4330',
 626: '4340',
 627: 'nan',
 628: 'nan',
 629: 'nan',
 630: 'nan',
 631: 'nan',
 632: 'nan',
 633: 'nan',
 634: 'nan',
 635: 'nan',
 636: 'nan',
 637: 'nan',
 638: 'nan',
 639: 'nan',
 640: 'nan',
 641: 'nan',
 642: 'nan',
 643: 'nan',
 644: 'nan',
 645: 'TAJ2',
 646: 'TAJ2',
 647: 'TAJ2',
 648: 'TAJ2',
 649: 'TAJ2',
 650: 'TAJ2',
 651: 'TAJ2',
 652: 'TAJ2',
 653: 'TAJ2',
 654: 'TAJ2',
 655: 'TAJ2',
 656: 'TAJ2',
 657: 'TAJ2',
 658: 'TAJ2',
 659: 'TAJ2',
 660: 'TAJ2',
 661: 'TAJ2',
 662: 'TTH2',
 663: 'TTM1',
 664: 'TTM1',
 665: 'TTM1',
 666: 'TTM1',
 667: 'TTM1',
 668: 'TTM1',
 669: 'TTM1',
 670: 'TTM1',
 671: 'STT1',
 672: 'STT1',
 673: 'TTT1',
 674: 'TTT1',
 675: 'TTT1',
 676: 'TTT1',
 677: 'TTT1',
 678: 'nan',
 679: 'nan',
 680: 'nan',
 681: 'nan',
 682: 'nan',
 683: 'nan',
 684: 'nan',
 685: 'nan',
 686: 'nan',
 687: 'nan',
 688: 'nan',
 689: 'nan',
 690: 'nan',
 691: 'nan',
 692: 'nan',
 693: 'nan',
 694: 'nan',
 695: 'nan',
 696: 'nan',
 697: 'nan',
 698: 'nan',
 699: 'nan',
 700: 'nan',
 701: 'nan',
 702: 'nan',
 703: 'nan',
 704: 'nan',
 705: 'nan',
 706: 'nan',
 707: 'nan',
 708: 'nan',
 709: 'nan',
 710: 'nan',
 711: 'nan',
 712: 'nan',
 713: 'nan',
 714: 'nan',
 715: 'nan',
 716: 'nan',
 717: 'nan',
 718: 'nan',
 719: 'nan',
 720: 'nan',
 721: 'nan',
 722: 'nan',
 723: 'nan',
 724: 'nan',
 725: 'nan',
 726: 'nan',
 727: 'nan',
 728: 'nan',
 729: 'nan',
 730: 'nan',
 731: '2717',
 732: '2717',
 733: '2717',
 734: '2717',
 735: '2717',
 736: '2717',
 737: '2717',
 738: '2948',
 739: '2948',
 740: '2948',
 741: '2948',
 742: '2948',
 743: '2948',
 744: '2948',
 745: '2948',
 746: '2948',
 747: '2948',
 748: '2948',
 749: '2948',
 750: '2948',
 751: '2948',
 752: '2948',
 753: '2948',
 754: '2948',
 755: '2948',
 756: '2948',
 757: '2948',
 758: '2948',
 759: '2948',
 760: '2948',
 761: '2948',
 762: '2948',
 763: '2948',
 764: '2948',
 765: '2948',
 766: 'nan',
 767: 'nan',
 768: 'nan',
 769: 'nan',
 770: 'nan',
 771: 'nan',
 772: 'nan',
 773: 'nan',
 774: 'nan',
 775: 'nan',
 776: 'nan',
 777: 'nan',
 778: 'nan',
 779: 'nan',
 780: 'nan',
 781: 'nan',
 782: 'nan',
 783: 'nan',
 784: 'nan',
 785: 'nan',
 786: 'nan',
 787: 'nan',
 788: 'nan',
 789: 'nan',
 790: 'nan',
 791: 'nan',
 792: 'nan',
 793: 'nan',
 794: 'nan',
 795: 'nan',
 796: 'nan',
 797: 'nan',
 798: 'nan',
 799: 'nan',
 800: 'nan',
 801: 'nan',
 802: 'nan',
 803: 'nan',
 804: 'nan',
 805: 'nan',
 806: 'nan',
 807: 'nan',
 808: 'nan',
 809: '3003',
 810: '3003',
 811: '3003',
 812: '3003',
 813: '3003',
 814: '3003',
 815: '3003',
 816: '3003',
 817: 'nan',
 818: 'nan',
 819: 'nan',
 820: 'nan',
 821: 'nan',
 822: 'nan',
 823: 'nan',
 824: 'nan',
 825: 'nan',
 826: 'nan',
 827: 'nan',
 828: 'nan',
 829: 'nan',
 830: 'nan',
 831: 'nan',
 832: 'nan',
 833: 'nan',
 834: 'nan',
 835: 'nan',
 836: 'nan',
 837: 'nan',
 838: 'nan',
 839: 'nan',
 840: 'nan',
 841: 'nan',
 842: 'nan',
 843: 'nan',
 844: 'nan',
 845: 'nan',
 846: 'nan',
 847: 'nan',
 848: 'nan',
 849: 'nan',
 850: 'nan',
 851: 'nan',
 852: 'nan',
 853: 'nan',
 854: 'nan',
 855: 'nan',
 856: 'nan',
 857: 'nan',
 858: 'nan',
 859: 'nan',
 860: 'nan',
 861: 'nan',
 862: 'nan',
 863: 'nan',
 864: 'nan',
 865: 'nan',
 866: 'nan',
 867: 'nan',
 868: 'nan',
 869: 'nan',
 870: 'nan',
 871: 'TCJ4',
 872: 'TCJ4',
 873: 'TCJ4',
 874: 'TCJ4',
 875: 'TCJ4',
 876: 'TCJ4',
 877: 'TCJ4',
 878: 'TCJ4',
 879: 'TCJ4',
 880: 'TCJ4',
 881: 'TCJ4',
 882: 'TCJ4',
 883: 'TCJ4',
 884: 'TCJ4',
 885: 'TCJ4',
 886: 'TCJ4',
 887: 'TCJ4',
 888: 'TCJ4',
 889: 'TCJ4',
 890: 'TCJ4',
 891: 'TCJ4',
 892: 'TCJ4',
 893: 'TCJ4',
 894: 'TCJ4',
 895: 'TCJ4',
 896: 'TCJ4',
 897: 'TCJ4',
 898: 'TCJ4',
 899: 'TCJ4',
 900: 'TCJ4',
 901: 'TCJ4',
 902: 'TCJ4',
 903: 'TCJ4',
 904: 'nan',
 905: 'nan',
 906: 'nan',
 907: 'nan',
 908: 'nan',
 909: 'nan',
 910: 'nan',
 911: 'nan',
 912: 'nan',
 913: 'nan',
 914: 'nan',
 915: 'nan',
 916: 'nan',
 917: 'nan',
 918: 'nan',
 919: 'nan',
 920: 'nan',
 921: 'TTM1',
 922: 'TTM1',
 923: 'TTM1',
 924: 'TTM1',
 925: 'TTM1',
 926: 'TTM2',
 927: 'TTM2',
 928: 'TTM2',
 929: 'TTM2',
 930: 'TTM2',
 931: 'TTM2',
 932: 'TTM2',
 933: 'TTM2',
 934: 'TTM2',
 935: 'TTM2',
 936: 'TTH1',
 937: 'TTH1',
 938: 'TTH1',
 939: 'TTH1',
 940: 'TTH1',
 941: 'TTH1',
 942: 'TTH1',
 943: 'TTH1',
 944: 'TTH1',
 945: 'TTH1',
 946: 'TTH1',
 947: 'TTH1',
 948: 'TTH1',
 949: 'TTH1',
 950: 'TTH1',
 951: 'TTH1',
 952: 'TTH1',
 953: 'TTH1',
 954: 'TTH1',
 955: 'TTH1',
 956: 'TTH1',
 957: 'TTH1',
 958: 'TTH1',
 959: 'TTH1',
 960: 'TTH1',
 961: 'TTH1',
 962: 'TTH1',
 963: 'TTH1',
 964: 'TTH1',
 965: 'TTH1',
 966: 'TTH1',
 967: 'TTH1',
 968: 'TTH1',
 969: 'TTH1',
 970: 'TTH1',
 971: 'TTH1',
 972: 'TTH1',
 973: 'TTH1',
 974: 'TTH1',
 975: 'TTH1',
 976: 'TTH1',
 977: 'TTH1',
 978: 'TTH1',
 979: 'TTH1',
 980: 'TTH1',
 981: 'TTH1',
 982: 'TTH1',
 983: 'TTH1',
 984: 'TTH1',
 985: 'TTH1',
 986: 'TTH1',
 987: 'TTH1',
 988: 'TTH1',
 989: 'TTH1',
 990: 'TTH1',
 991: 'TTH1',
 992: 'TTH1',
 993: 'TTH1',
 994: 'TTH1',
 995: 'TTH1',
 996: 'TTH1',
 997: 'TTH1',
 998: 'TTH1',
 999: 'TTH1',
 ...}

In [224]:
#Enlever les nan

index_to_code_no_nan = dict( [[a,b] for a,b in index_to_code.items() if b != 'nan'])

In [130]:
pers= hackhaton['ID_CARRIERE']

143

In [166]:
#Recuperer les indices du passage d'un ind a un autre individu, exactement : la dernière année de chaque individus

ind_pers=[i for i in range(0,len(pers)-1) if pers[i] != pers[i+1]]

In [230]:
len(ind_pers)

14009

In [228]:
i_to_code=pd.DataFrame.from_dict(index_to_code_no_nan, orient='index')
i_to_code=i_to_code.reset_index()
i_to_code

          index     0
0            49  TNJ2
1            50  TNJ2
2            51  TNJ2
3            52  TNJ2
4            53  TNJ2
...         ...   ...
480752  1048555  1314
480753  1048556  1314
480754  1048557  1314
480755  1048558  1314
480756  1048559  1314

[480757 rows x 2 columns]

In [233]:
L=[]
a=0
c=1
for i in ind_pers:
    
    for j in range(0,i-a): 
        L.append(c)
    
    a=i
    c=c+1

In [ ]:
for i in range(0,
    for i in index

In [235]:
ind_pers

[103,
 145,
 246,
 288,
 322,
 351,
 383,
 463,
 484,
 505,
 626,
 677,
 765,
 818,
 903,
 935,
 1036,
 1079,
 1132,
 1327,
 1402,
 1463,
 1545,
 1645,
 1689,
 1746,
 1797,
 1850,
 2186,
 2245,
 2297,
 2429,
 2472,
 2543,
 2604,
 2645,
 2736,
 2785,
 2833,
 2870,
 2927,
 3015,
 3200,
 3260,
 3332,
 3377,
 3464,
 3537,
 3595,
 3610,
 3709,
 3757,
 3803,
 3865,
 3939,
 3996,
 4034,
 4066,
 4277,
 4450,
 4511,
 4539,
 4605,
 4658,
 4751,
 4806,
 4830,
 4951,
 5006,
 5062,
 5101,
 5172,
 5220,
 5240,
 5289,
 5351,
 5395,
 5510,
 5590,
 5668,
 5739,
 5778,
 5822,
 5870,
 5932,
 6036,
 6137,
 6199,
 6283,
 6381,
 6439,
 6511,
 6609,
 6683,
 6728,
 6907,
 6994,
 7156,
 7213,
 7449,
 7503,
 7528,
 7567,
 7641,
 7757,
 7811,
 7850,
 7901,
 7953,
 8005,
 8438,
 8493,
 8546,
 8574,
 8605,
 8669,
 8698,
 8734,
 8780,
 8850,
 8962,
 9023,
 9055,
 9103,
 9281,
 9327,
 9388,
 9445,
 9508,
 9534,
 9681,
 9756,
 9791,
 9831,
 9872,
 10017,
 10038,
 10347,
 10488,
 10842,
 10865,
 10965,
 11022,
 11059,
 11111,
 11169,
 11210,
 11438,
 11507,
 11524,
 11575,
 11630,
 11677,
 11748,
 11866,
 11923,
 11953,
 12000,
 12051,
 12093,
 12160,
 12210,
 12273,
 12483,
 12508,
 12606,
 12649,
 12693,
 12748,
 12771,
 12875,
 12939,
 12992,
 13016,
 13187,
 13368,
 13582,
 13618,
 13669,
 13749,
 13813,
 13849,
 13935,
 13959,
 14067,
 14324,
 14419,
 14561,
 14643,
 14691,
 14739,
 14802,
 14850,
 14924,
 15018,
 15097,
 15159,
 15203,
 15256,
 15390,
 15431,
 15477,
 15506,
 15559,
 15879,
 15983,
 16148,
 16251,
 16304,
 16327,
 16391,
 16431,
 16492,
 16557,
 16591,
 16652,
 16687,
 16743,
 16860,
 16956,
 17021,
 17099,
 17156,
 17284,
 17371,
 17421,
 17682,
 17823,
 17901,
 18085,
 18149,
 18234,
 18310,
 18357,
 18407,
 18493,
 18514,
 18610,
 18678,
 18711,
 18864,
 18964,
 19051,
 19150,
 19286,
 19434,
 19469,
 19722,
 19758,
 19775,
 19868,
 19900,
 19937,
 19974,
 20029,
 20083,
 20133,
 20211,
 20268,
 20329,
 20382,
 20493,
 20591,
 20663,
 20724,
 20761,
 20779,
 20831,
 20888,
 20950,
 20993,
 21016,
 21036,
 21075,
 21140,
 21190,
 21303,
 21381,
 21419,
 21474,
 21538,
 21597,
 21718,
 21767,
 21835,
 21914,
 21980,
 22161,
 22215,
 22253,
 22285,
 22327,
 22376,
 22427,
 22480,
 22525,
 22687,
 22723,
 22850,
 22907,
 22970,
 23003,
 23090,
 23207,
 23310,
 23375,
 23431,
 23479,
 23538,
 23584,
 23650,
 23721,
 23757,
 23843,
 23882,
 24025,
 24089,
 24278,
 24315,
 24357,
 24459,
 24525,
 24592,
 24721,
 24784,
 24950,
 25005,
 25056,
 25094,
 25720,
 25798,
 25825,
 25875,
 26018,
 26052,
 26206,
 26270,
 26366,
 26435,
 26483,
 26532,
 27139,
 27218,
 27242,
 27373,
 27469,
 27536,
 27606,
 27710,
 27752,
 27801,
 27864,
 27990,
 28097,
 28122,
 28171,
 28194,
 28244,
 28361,
 28462,
 28495,
 28542,
 28623,
 28703,
 28785,
 28847,
 28895,
 28949,
 28999,
 29054,
 29092,
 29133,
 29201,
 29255,
 29292,
 29361,
 29424,
 29489,
 29534,
 29582,
 29643,
 29785,
 29861,
 29910,
 29986,
 30042,
 30092,
 30200,
 30269,
 30318,
 30356,
 30494,
 30555,
 30601,
 30647,
 30728,
 30801,
 30847,
 30955,
 31004,
 31035,
 31062,
 31135,
 31193,
 31245,
 31309,
 31382,
 31462,
 31539,
 31610,
 31729,
 31735,
 31828,
 31882,
 31915,
 31972,
 32051,
 32079,
 32120,
 32154,
 32204,
 32259,
 32371,
 32416,
 32470,
 32506,
 33122,
 33172,
 33248,
 33291,
 33361,
 33474,
 33535,
 33607,
 33702,
 33745,
 33833,
 33900,
 34034,
 34095,
 34120,
 34160,
 34211,
 34302,
 34427,
 34478,
 34614,
 34807,
 34965,
 35017,
 35071,
 35205,
 35278,
 35448,
 35483,
 35584,
 35656,
 35768,
 35838,
 35901,
 36103,
 36145,
 36191,
 36269,
 36304,
 36352,
 36364,
 36385,
 36467,
 36674,
 36736,
 37070,
 37127,
 37263,
 37301,
 37384,
 37406,
 37473,
 37533,
 37590,
 37611,
 37661,
 37762,
 37852,
 37887,
 38006,
 38065,
 38156,
 38238,
 38307,
 38365,
 38409,
 38557,
 38631,
 38694,
 38712,
 38800,
 38855,
 38971,
 39137,
 39156,
 39209,
 39240,
 39358,
 39470,
 39519,
 39615,
 39662,
 39753,
 39812,
 39839,
 39999,
 40053,
 40170,
 40237,
 40298,
 40333,
 40433,
 40477,
 40526,
 40586,
 40605,
 40688,
 40748,
 40812,
 40880,
 40934,
 41005,
 41097,
 41172,
 41239,
 41290,
 41328,
 41564,
 41664,
 41716,
 41768,
 41806,
 42184,
 42288,
 42312,
 42359,
 42451,
 42512,
 42593,
 42706,
 42762,
 42831,
 42858,
 42924,
 42977,
 43064,
 43104,
 43183,
 43269,
 43319,
 43388,
 43635,
 43747,
 43799,
 43863,
 43902,
 44084,
 44169,
 44239,
 44273,
 44370,
 44418,
 44468,
 44586,
 44612,
 44737,
 44778,
 44850,
 44919,
 45012,
 45197,
 45245,
 45288,
 45335,
 45379,
 45517,
 45537,
 45608,
 45700,
 45872,
 46003,
 46120,
 46205,
 46299,
 46422,
 46558,
 46608,
 46648,
 46706,
 46741,
 46819,
 46837,
 46891,
 46931,
 46966,
 47069,
 47146,
 47242,
 47294,
 47355,
 47457,
 47567,
 47618,
 47674,
 47712,
 47753,
 47791,
 47827,
 47946,
 47970,
 48040,
 48116,
 48147,
 48209,
 48250,
 48289,
 48361,
 48416,
 48569,
 48614,
 48706,
 48762,
 48774,
 48947,
 49023,
 49147,
 49280,
 49338,
 49379,
 49447,
 49540,
 49624,
 49687,
 49740,
 49776,
 49835,
 49906,
 50166,
 50249,
 50307,
 50376,
 50518,
 50693,
 50758,
 50785,
 50845,
 50896,
 50914,
 50959,
 50996,
 51040,
 51076,
 51120,
 51251,
 51317,
 51373,
 51420,
 51640,
 51677,
 51814,
 51881,
 51948,
 52063,
 52134,
 52191,
 52246,
 52315,
 52370,
 52422,
 52495,
 52532,
 52574,
 52651,
 52912,
 52953,
 53023,
 53159,
 53210,
 53240,
 53517,
 53590,
 53636,
 53653,
 53797,
 53852,
 53909,
 53964,
 53995,
 54055,
 54214,
 54273,
 54332,
 54388,
 54439,
 54687,
 54710,
 54776,
 54781,
 54852,
 54921,
 54946,
 55008,
 55051,
 55263,
 55287,
 55316,
 55360,
 55410,
 55423,
 55495,
 55533,
 55630,
 55674,
 55822,
 55869,
 55937,
 56052,
 56098,
 56156,
 56201,
 56344,
 56387,
 56447,
 56476,
 56539,
 56606,
 56688,
 56754,
 56784,
 56832,
 56875,
 56961,
 57021,
 57063,
 57235,
 57289,
 57339,
 57397,
 57519,
 57638,
 57726,
 57757,
 57798,
 57871,
 57912,
 57941,
 57992,
 58027,
 58134,
 58219,
 58234,
 58267,
 58294,
 58352,
 58395,
 58486,
 58580,
 58739,
 58850,
 58871,
 58938,
 58964,
 59033,
 59069,
 59137,
 59208,
 59255,
 59373,
 59420,
 59522,
 59577,
 59656,
 59696,
 59745,
 59764,
 59800,
 59835,
 59891,
 59943,
 60020,
 60095,
 60165,
 60273,
 60381,
 60444,
 60460,
 60571,
 60639,
 60745,
 60805,
 60875,
 60917,
 60943,
 60976,
 61011,
 61053,
 61104,
 61250,
 61298,
 61355,
 61389,
 61438,
 61490,
 61522,
 61553,
 61610,
 61678,
 61771,
 61822,
 61881,
 62030,
 62079,
 62205,
 62236,
 62276,
 62334,
 62531,
 62634,
 62670,
 62710,
 62792,
 62866,
 62935,
 62957,
 63314,
 63345,
 63383,
 63658,
 63806,
 64085,
 64121,
 64178,
 64216,
 64263,
 64326,
 64371,
 64478,
 64553,
 64712,
 64752,
 64920,
 64940,
 65002,
 65135,
 65203,
 65277,
 65324,
 65392,
 65451,
 65619,
 65676,
 65758,
 65791,
 65889,
 65936,
 65974,
 66015,
 66064,
 66123,
 66143,
 66191,
 66255,
 66297,
 66337,
 66378,
 66425,
 66442,
 66619,
 66644,
 66715,
 66811,
 67075,
 67120,
 67221,
 67250,
 67291,
 67372,
 67463,
 67506,
 67611,
 67650,
 67682,
 67781,
 67840,
 67864,
 67934,
 68060,
 68104,
 68173,
 68246,
 68291,
 68336,
 68445,
 68521,
 68791,
 68833,
 69065,
 69137,
 69172,
 69207,
 69259,
 69313,
 69409,
 69459,
 69477,
 70134,
 70219,
 70300,
 70384,
 70537,
 70721,
 70852,
 70912,
 71004,
 71055,
 71115,
 71163,
 71191,
 71249,
 71405,
 71465,
 71515,
 71587,
 71769,
 71903,
 71975,
 72020,
 72067,
 72104,
 72216,
 72271,
 72613,
 72657,
 72743,
 72784,
 72833,
 72865,
 72890,
 72956,
 73020,
 73150,
 73215,
 73342,
 73400,
 73434,
 73519,
 73566,
 73607,
 73694,
 73751,
 73780,
 73833,
 73912,
 74028,
 74098,
 74169,
 74338,
 74411,
 74494,
 74533,
 74605,
 74670,
 74721,
 74769,
 74860,
 74921,
 75006,
 75134,
 75437,
 75479,
 75522,
 75649,
 75803,
 75896,
 75973,
 76042,
 76177,
 76214,
 76279,
 76346,
 76416,
 76455,
 76505,
 76562,
 76667,
 76718,
 76833,
 76859,
 77022,
 77051,
 77108,
 77174,
 77222,
 77267,
 ...]